# Generated by Django 5.2 on 2025-05-08 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_type', models.CharField(choices=[('text', 'Text'), ('boolean', 'Yes/No'), ('choice', 'Multiple Choice'), ('date', 'Date'), ('file', 'File Upload')], default='text', max_length=20)),
                ('choice_options', models.TextField(blank=True, help_text="Comma-separated options for 'choice' type", null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceWorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('requires_review', 'Requires Review'), ('passed', 'Passed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='pending', max_length=20)),
                ('credas_check_id', models.CharField(blank=True, help_text='Reference ID from Credas check', max_length=100, null=True)),
                ('credas_result', models.TextField(blank=True, null=True)),
                ('peps_sanctions_check_id', models.CharField(blank=True, help_text='Reference ID from PEPs/Sanctions check', max_length=100, null=True)),
                ('peps_sanctions_result', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the check', null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.matter')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.complianceworkflowtemplate')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_boolean', models.BooleanField(blank=True, null=True)),
                ('answer_choice', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_date', models.DateField(blank=True, null=True)),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='compliance_files/%Y/%m/%d/')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('compliance_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='compliance.compliancecheck')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.compliancequestion')),
            ],
            options={
                'ordering': ['question__id'],
                'unique_together': {('compliance_check', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceWorkflowTemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.compliancequestion')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.complianceworkflowtemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'question')},
            },
        ),
    ]
