# Generated by Django 5.2 on 2025-05-15 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matter',
            options={'ordering': ['-protocol_number']},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['-initiated_at']},
        ),
        migrations.RemoveConstraint(
            model_name='workflow',
            name='unique_matter_workflow',
        ),
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='matter',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='matters', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='matter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matter',
            name='protocol_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='ai_generated_steps',
            field=models.JSONField(blank=True, help_text='AI-suggested workflow steps (JSON array)', null=True),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
    ]
